export const Users = [
  {
    id:1,
    profilePicture: "assets/1.jpg",
    username: "William Stamp",
  },
  {
    id:2,
    profilePicture: "assets/2.jpg",
    username: "Chris Pinto",
  },
  {
    id:3,
    profilePicture: "assets/3.jpg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "assets/4.jpg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "assets/5.jpg",
    username: "Mark Hannem",
  },
  {
    id:6,
    profilePicture: "assets/6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "assets/7.jpg",
    username: "Travis Bennett",
  },
  {
    id:8,
    profilePicture: "assets/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id:9,
    profilePicture: "assets/9.jpg",
    username: "Gary Duty",
  },
  {
    id:10,
    profilePicture: "assets/10.jpg",
    username: "Justin Trudeau",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Cod fishing with the lil man and girlfriends family on this beautiful day!",
    photo: "assets/1.1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "The workstation",
    photo: "assets/gaming.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Got a lot of work done today!",
    photo: "assets/feed1.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    desc: "None of this makes any sense!! Please help!",
    photo: "assets/feed2.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "Me when Will and Chris ask who farted...HAHAHA",
    photo: "assets/feed4.webp",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/6.1.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Trip to Japan for a buisness meeting!",
    photo: "assets/feed5.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    desc: "I lost my potato.......again",
    photo: "",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "I found a potato!!",
    photo: "assets/feed6.jpg",
    date: "3 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    desc: "Is that you daddy??!! ",
    photo: "assets/feed7.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];